// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WFCRUD.Models;

[Index("Crs_Id", Name = "IX_CourseSessions_Crs_Id")]
[Index("Ins_Id", Name = "IX_CourseSessions_Ins_Id")]
public partial class CourseSession
{
    [Key]
    public int CourseSessionId { get; set; }

    public int? Ins_Id { get; set; }

    public int? Crs_Id { get; set; }

    [StringLength(255)]
    public string Title { get; set; }

    public DateTime Crs_Date { get; set; }

    [InverseProperty("CourseSession")]
    public virtual ICollection<CourseSessionAttendance> CourseSessionAttendances { get; set; } = new List<CourseSessionAttendance>();

    [ForeignKey("Crs_Id")]
    [InverseProperty("CourseSessions")]
    public virtual Course Crs { get; set; }

    [ForeignKey("Ins_Id")]
    [InverseProperty("CourseSessions")]
    public virtual Instructor Ins { get; set; }
}