// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WFCRUD.Models;

[Index("Dept_Manager", Name = "IX_Departments_Dept_Manager", IsUnique = true)]
public partial class Department
{
    [Key]
    public int Dept_Id { get; set; }

    [StringLength(255)]
    public string Dept_Name { get; set; }

    [StringLength(255)]
    public string Dept_Location { get; set; }

    public int? Dept_Manager { get; set; }

    [InverseProperty("Dept")]
    public virtual ICollection<Course> Courses { get; set; } = new List<Course>();

    [ForeignKey("Dept_Manager")]
    [InverseProperty("Department")]
    public virtual Instructor Dept_ManagerNavigation { get; set; }

    [InverseProperty("Dept")]
    public virtual ICollection<Instructor> Instructors { get; set; } = new List<Instructor>();
}