// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WFCRUD.Models;

public partial class Student
{
    [Key]
    public int St_Id { get; set; }

    [Required]
    [StringLength(255)]
    public string St_Fname { get; set; }

    [StringLength(10)]
    public string St_Lname { get; set; }

    public string St_Phone { get; set; }

    [InverseProperty("Student")]
    public virtual ICollection<CourseSessionAttendance> CourseSessionAttendances { get; set; } = new List<CourseSessionAttendance>();

    [ForeignKey("St_Id")]
    [InverseProperty("Sts")]
    public virtual ICollection<Course> Crs { get; set; } = new List<Course>();
}